### ISSUE TITLE
Sublime Text 3配置Less

### ISSUE THREAD

**Issue by holyzfy** [holyzfy/frontend_guidelines#9]
## 最终效果

保存`.less`文件时会当前目录下生成同名的css文件，并且自动给css3属性打前缀
## 安装说明
1. 安装[sublime-less2css](https://github.com/timdouglas/sublime-less2css)
2. 安装[less-plugin-autoprefix](https://github.com/less/less-plugin-autoprefix)
3. 菜单`Preferences` > `Package Control: Install Package`，依次安装
   - Less
   - Less2Css
4. 菜单`Preferences` > `Settings` > `Less2Css` > `Settings - User`，增加
   
   ``` json
   {
       "lesscCommand": "{{lessc_path}}",
       "minify": false,
       "autoprefix": true
   }
   ```
   
   在终端里运行`which lessc`，把输出的内容替换掉上面的{{lessc_path}}
## 测试一下吧

新建文件`test.less`，内容如下：

``` css
.test {
    margin: 0;
    font-size: 14px;
    .item {
        display: flex;
        line-height: 1.5;
    }
}
```

保存less后查看当前目录下生成的`demo.css`
